lzc-sdk-version: '0.1'
name: netdata
package: cloud.lazycat.app.netdata
version: 2.4.0-1
application:
  routes:
    - /=http://netdata.cloud.lazycat.app.netdata.lzcapp:19999
  subdomain: netdata
  ingress:
    - protocol: tcp
      port: 19999
      service: netdata
services:
  netdata: 
    # origin image: netdata/netdata:v2.4.0
    image: registry.lazycat.cloud/u11408144/netdata/netdata:99ad366ae2ca587f
    binds:
      - /lzcapp/var/config:/etc/netdata
      - /lzcapp/var/data:/var/lib/netdata
      - /lzcapp/var/cache:/var/cache/netdata
    environment:
